version: '3.1'
services:
  postgresql:
    image: postgres:latest
    ports:
      - '8080:8080'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=9mRE